/**
 * Router Types
 *
 * What: Type definitions for endpoint registry and routing
 * How: Interfaces for endpoint metadata and registry
 * Why: Provides type safety for route management
 */

// TODO: Full implementation in Task 1.4: Hono Router

/**
 * HTTP methods supported by the router
 * Includes all methods defined in OpenAPI specification
 */
export type HttpMethod = 'get' | 'post' | 'put' | 'patch' | 'delete' | 'options' | 'head' | 'trace';

/**
 * Security requirement from OpenAPI spec
 */
export interface SecurityRequirement {
  name: string;
  scopes: string[];
}

/**
 * Registry entry for a single endpoint
 */
export interface EndpointEntry {
  operationId: string;
  method: HttpMethod;
  path: string;
  summary?: string;
  description?: string;
  tags: string[];
  responseSchema?: string;
  hasHandler: boolean;
  hasSeed: boolean;
  security: SecurityRequirement[];
}

/**
 * Statistics about the endpoint registry
 */
export interface RegistryStats {
  totalEndpoints: number;
  withCustomHandler: number;
  totalSchemas: number;
  withCustomSeed: number;
  autoGenerated: number;
}

/**
 * Registry of all endpoints
 */
export interface EndpointRegistry {
  endpoints: Map<string, EndpointEntry>;
  byTag: Map<string, EndpointEntry[]>;
  byPath: Map<string, EndpointEntry[]>;
  stats: RegistryStats;
}
